packages:
    - "apps/**/*"
    - "packages/**/*"
    - "!**/.next/**"
    - "!**/dist/**"

catalog:
  viem: 2.17.5
  zod: 3.22.4
  "@solana/web3.js": 1.95.1
  "@ethersproject/providers": 5.7.2
  "@ethersproject/transactions": 5.7.0
  "@ethersproject/address": 5.7.0
  "@ethersproject/constants": 5.7.0
  "@ethersproject/contracts": 5.7.0
  "@ethersproject/wallet": 5.7.0
  "@ethersproject/bytes": 5.7.0
  "@ethersproject/abstract-provider": 5.7.0
