name: CI
on:
    push:
        branches-ignore:
            - main

jobs:
    build-and-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Build all
              run: pnpm build

            - name: Test all
              run: pnpm test
