name: CI
on:
    push:
env:
    NODE_VERSION: 18.15.0
    YARN_VERSION: 1.22.19
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    lint-and-format:
        name: Lint and format
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-environment
              with:
                  node-version: "${{ env.NODE_VERSION }}"
                  yarn-version: "${{ env.YARN_VERSION }}"
            - name: Run ESLint and check Prettier formatting
              run: yarn run lint
    build-and-test:
        name: Build and test
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-environment
              with:
                  node-version: "${{ env.NODE_VERSION }}"
                  yarn-version: "${{ env.YARN_VERSION }}"
            - run: yarn run build
            - run: yarn run test
        timeout-minutes: 15
