name: CI
on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build-and-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.3.0

            - name: Set Node.js 18.16.0
              uses: actions/setup-node@v3
              with:
                  node-version: 18.16.0
                  cache: "pnpm"

            - name: Run install
              run: pnpm install --frozen-lockfile

            - name: Build all
              run: pnpm build

            - name: Test all
              run: pnpm test

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: [build-and-test]
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.3.0

            - name: Set Node.js 18.16.0
              uses: actions/setup-node@v3
              with:
                  node-version: 18.16.0
                  cache: "pnpm"

            - name: Run install
              run: pnpm install --frozen-lockfile

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1
              with:
                  commit: "Release packages"
                  title: "Release packages"
                  publish: pnpm changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
