name: Pull Request Stats (Slack)

on:
    schedule:
        - cron: "0 11 * * 1-5"

jobs:
    stats:
        runs-on: ubuntu-latest
        steps:
            - name: Send pull request stats to slack
              uses: flowwer-dev/pull-request-stats@master
              with:
                  period: 14
                  charts: true
                  sortBy: "REVIEWS"
                  slackChannel: "#project-prs"
                  slackWebhook: "https://hooks.slack.com/services/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"