name: Prettier-Lint

on:
    push:
        branches-ignore:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.12.2]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}
                  # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
                  persist-credentials: false

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Check for unpretty files
              run: pnpm prettier:check

    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.12.2]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - run: pnpm lint
